# Generated by Django 4.2.20 on 2026-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("excerpt", models.TextField(max_length=500)),
                ("body", models.TextField()),
                (
                    "author",
                    models.CharField(default="MbazaNLP Community", max_length=100),
                ),
                ("published", models.DateField()),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published"],
            },
        ),
    ]
